export { adaptMailDraft } from './adapter'
export { assessCreate, EasyMailCreateService } from './create-service'
export { buildMailCustomerParams, filesMatch, formatRecipientList, readMailCustomer, readSaveMailInfo } from './contracts'
export { productionGate, mailWritesEnabled, liveWriteBlockers, encodeRelatedFileIds } from './gate'
export { readCustomerFlow, readForeignPic, readMailNameRules, readWordRules } from './page-reads'
export type { MailWriteGate } from './gate'
export { isMailDraftPreview, isMailExecutionView } from './guards'
export { EasyMailReadService } from './read-service'
export { MailExecutionRuntime } from './runtime'
export { EasyMailSaveService } from './save-service'
export { applyEvent, blocksAnotherCreate, nextState } from './state'
export { ExecutionStore, MemoryExecutionStore, executionStorageKey } from './store'
export type { EasyMailDraft, EasyMailSnapshot, MailExecutionRecord, MailExecutionState, MailExecutionView } from './types'
