export { CONTRACT_EVIDENCE, evidenceFor } from './contract-evidence'
export { ExecutionCoordinator, CROSS_TAB_WRITE_EXCLUSION_PROVEN, allowsProductionWrite, processLocalLock, browserLock } from './coordinator'
export { appendCheckpoint, markRequestSent, markUnknown } from './checkpoint'
export { runDryRun } from './dry-run'
export { prepareStage } from './executor'
export { createLog, exportDiagnostic } from './logger'
export { recoverTask } from './recovery'
export { MemoryTaskRepository, TaskRepository } from './repository'
export { STAGES, WRITE_STAGES } from './state'
export { buildTask, taskFingerprint } from './task-builder'
export { validateTask } from './task-validator'
export type { DryRunResult } from './dry-run'
export type { AutomationTask, AutomationTaskItem, AutomationTaskState } from './types'
