export { assembleMail, fillFromRules } from './assemble'
export { planDrafts } from './planner'
export { buildDraftPreview } from './preview'
export { planMailGroups } from './rules/grouping'
export { mappingKey, matchMailType, resolveMailType, upsertMapping } from './rules/description-mapping'
export { policyRemark, policySetKey, removeCustomerPolicy, upsertCustomerPolicy } from './rules/customer-policy'
export { selectionFingerprint } from './fingerprint'
export { buildSubject, injectCount } from './rules/subject-builder'
export { buildBody } from './rules/body-builder'
export { resolveRecipients, uniqueAddresses } from './rules/recipient-resolver'
export { emptyMailRules, MailRuleRepository, mailStorageKey, readMailRules } from './repository'
export { applyConfirmedBind, bindCustomer, reviewCustomerBind, selectPage, toSelectedFile, toggleSelected } from './selection'
export type { MailDraftPreview, MailRuleBundle, SelectedPatentFile, SelectionSnapshot } from './types'
