export { planDrafts } from './planner'
export { buildDraftPreview } from './preview'
export { planMailGroups } from './rules/grouping'
export { matchMailType } from './rules/description-mapping'
export { buildSubject, injectCount } from './rules/subject-builder'
export { buildBody } from './rules/body-builder'
export { resolveRecipients, uniqueAddresses } from './rules/recipient-resolver'
export { emptyMailRules, MailRuleRepository, mailStorageKey, readMailRules } from './repository'
export { bindCustomer, selectPage, toSelectedFile, toggleSelected } from './selection'
export type { MailDraftPreview, MailRuleBundle, SelectedPatentFile, SelectionSnapshot } from './types'
